name: build for docker
on: [push]
run-name: ${{ github.event.commits[0].message }}
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Launch Builder
        run: |
          export build_repo_addr='registry.cn-hangzhou.aliyuncs.com'
          docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} ${build_repo_addr} \
          && docker build . -t registry.cn-hangzhou.aliyuncs.com/bohai_repo/k8s-wiki:latest \
          && docker push registry.cn-hangzhou.aliyuncs.com/bohai_repo/k8s-wiki:latest